//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivalScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public int Value { get; set; }
        public string Color { get; set; }
        public bool Show { get; set; }
        public int Length { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string Company { get; set; }
        public string PrimaryFirstName { get; set; }
        public string PrimaryLastName { get; set; }
        public string PrimaryAddress { get; set; }
        public string PrimaryCity { get; set; }
        public string PrimaryProvState { get; set; }
        public string PrimaryCountry { get; set; }
        public string PrimaryPCZip { get; set; }
        public string PrimaryPhone { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryFirstName { get; set; }
        public string SecondaryLastName { get; set; }
        public string SecondaryAddress { get; set; }
        public string SecondaryCity { get; set; }
        public string SecondaryPovState { get; set; }
        public string SecondaryCountry { get; set; }
        public string SecondaryPCZip { get; set; }
        public string SecondaryPhone { get; set; }
        public string SecondaryEmail { get; set; }
        public string CastMembers { get; set; }
        public string Playwright { get; set; }
        public string Director { get; set; }
        public string StageManager { get; set; }
        public string Designer { get; set; }
        public string TeamSize { get; set; }
        public string NewWork { get; set; }
        public string Genre { get; set; }
        public string GenreOther { get; set; }
        public string ShowRating { get; set; }
        public string AgeRestriction { get; set; }
        public string ShowContains { get; set; }
        public string ContentAdvisory { get; set; }
        public string GeneralAdmission { get; set; }
        public string StudentSenior { get; set; }
        public string ShowDescription { get; set; }
        public string Website { get; set; }
        public string ShowImage { get; set; }
        public string NameonCheque { get; set; }
        public string CompanyNameonCheque { get; set; }
        public string ChequeAddress { get; set; }
        public string ChequeCity { get; set; }
        public string ChequeProvState { get; set; }
        public string ChequeCountry { get; set; }
        public string ChequePCZip { get; set; }
        public string GST { get; set; }
        public string WhenNotAvailable { get; set; }
        public string Sharing { get; set; }
        public string SharingRef { get; set; }
        public string SharingCompany { get; set; }
        public string SharingShowTitle { get; set; }
        public string StagingRequirements { get; set; }
        public string Intermission { get; set; }
        public string LightingRequirements { get; set; }
        public string SoundRequirements { get; set; }
        public string Dancing { get; set; }
        public string DancingType { get; set; }
        public string Projection { get; set; }
        public string ImageSize { get; set; }
        public string ThrowDistance { get; set; }
        public string Holdovers { get; set; }
        public string ScreenElevation { get; set; }
        public string ScreenHeight { get; set; }
        public string ScreenWidth { get; set; }
        public string ProjectionRatio { get; set; }
        public string MediaType { get; set; }
        public string ShootFrom { get; set; }
        public string ShootFromOther { get; set; }
        public string ScreenMaterial { get; set; }
        public string SoundOut { get; set; }
        public string Liquids { get; set; }
        public string LiquidsDescribe { get; set; }
        public string OpenFlames { get; set; }
        public string Loud { get; set; }
        public string LoudDescribe { get; set; }
        public string Firearms { get; set; }
        public string Smoking { get; set; }
        public string FogMachine { get; set; }
        public string Strobe { get; set; }
        public string Hazer { get; set; }
        public string MoreLights { get; set; }
        public string WirelessMic { get; set; }
        public string Frequencies { get; set; }
        public string OtherEquipments { get; set; }
        public string EquipmentSpecify { get; set; }
        public string StageDesign { get; set; }
        public string SpecialNeeds { get; set; }
        public string Comments { get; set; }
        public string RehearsalTime { get; set; }
        public string ComingFrom { get; set; }
        public string FestivalComingFrom { get; set; }
        public string WhenArriving { get; set; }
        public string Release { get; set; }
        public string VenueName { get; set; }
        public string VenueAddress { get; set; }
        public string VenueTotal { get; set; }
        public string Wheelchair { get; set; }
        public string WheelchairCapacity { get; set; }
        public string Washrooms { get; set; }
        public string WheelchairWashrooms { get; set; }
        public string Alcohol { get; set; }
        public string Food { get; set; }
        public string EnterEarly { get; set; }
        public string MinutesBefore { get; set; }
        public string Bar { get; set; }
        public string Minors { get; set; }
        public string ShowDate { get; set; }
        public string PayDate { get; set; }
        public string PayMethod { get; set; }
        public string Amount { get; set; }
        public string Refund { get; set; }
        public string RefundDate { get; set; }
        public string DateEntered { get; set; }
        public string VenueNo { get; set; }
    }
}
