//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivalScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysEvent
    {
        public long ID { get; set; }
        public string Level { get; set; }
        public string Message { get; set; }
        public System.DateTime UpdateAt { get; set; }
        public string CreateBy { get; set; }
    }
}
